### ISSUE TITLE
Test coverage lacking

### ISSUE THREAD

**Issue by lukekrikorian** [CSC207-2022F-UofT/course-project-gordon-recipe#38]
Currently, our test coverage is a bit lacking.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/22383417/206010291-fe07599b-c329-4dcb-946c-5fc7a046cc51.png">

As in the image above, we're only at 69% method coverage for entities and 81% method coverage for use-cases. Even if we don't manage to find a way to test the TUI, it's a good idea to get method coverage to 100% for both entities and use-cases.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/22383417/206009867-0971bc94-034a-4644-b8e2-5e2d9e70f741.png">
An example of running test coverage in IntelliJ

**Comment by jasala10** [comment]
Thanks for pointing this out; I can definitely help. I can start by finishing up the use case tests, namely RecipeRecommender and RecipeManager (although Luke if you'd prefer to implement tests for your own use case just let me know and I can leave that for you) Hopefully I can finish up the entity tests as well.

**Comment by jasala10** [comment]
I've committed and pushed my changes to the new `test-coverage` branch. `RecipeRecommender`, `RecipeManager`, and `ChefMode` are now complete. All that's left as for usecase testing is one method in `RecipeSearcher`. I couldn't figure out how test it. Hopefully I can get to the entity testing soon.
